name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'template'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            target: 'x86_64-pc-windows-msvc'
            args: ''
          - platform: 'windows-latest'
            target: 'aarch64-pc-windows-msvc'
            args: '--target aarch64-pc-windows-msvc'

    runs-on: ${{ matrix.platform }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Install rust target
        run: rustup target add ${{ matrix.target }}

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install frontend dependencies
        run: pnpm install # change this to npm, pnpm or bun depending on which one you use.

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Regenerate Icons
        run: pnpm tauri icon

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: 'server'
          releaseName: 'server v__VERSION__'
          releaseBody: '溯源平台'
          releaseDraft: false
          prerelease: false
          publish: true
          args: ${{ matrix.args }}
